backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
local_backend: true # run npx netlify-cms-proxy-server for local testing

# publish_mode: editorial_workflow

media_folder: "static/assets"
public_folder: "/assets"

i18n:
  structure: single_file
  locales: [it, en]

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    identifier_field: title
    folder: "src/content/posts"
    slug: "{{fields.title}}"
    summary: "{{title}}"
    create: true
    i18n: true
    fields:
      - { name: "type", widget: "hidden", default: "post", i18n: duplicate }
      - { label: "Title", name: "title", widget: "string", tagname: "h1", i18n: duplicate }
      - { label: "Special Text", name: "special_text", widget: "string", i18n: true }
      - { label: "Article", name: "body", widget: "markdown", required: false, i18n: true }

  - label: "Pages"
    name: "pages"
    i18n: true
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        i18n: true
        fields:
          - { label: "Featured Title", name: "title", widget: "string", tagname: "h1", i18n: duplicate }
          - { label: "Subtitle", name: "subtitle", widget: "string", i18n: true }
          - { label: "Body", name: "body", widget: "markdown", required: false, i18n: true }
          - { name: "template", widget: "string", default: "index", i18n: duplicate }
          - { name: "type", widget: "string", default: "page", i18n: duplicate }
          - { name: "slug", widget: "string", default: "", i18n: duplicate }
        