backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing

# publish_mode: editorial_workflow

media_folder: "static/assets"
public_folder: "/assets"

collections:
  # - name: "posts"
  #   label: "Posts"
  #   label_singular: "Post"
  #   description: >
  #     Create awesome content here.
  #   folder: "src/content/posts"
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   summary: "{{title}} — {{year}}/{{month}}/{{day}}"
  #   create: true
  #   fields:
  #     - { label: "Template", name: "template", widget: "hidden", default: "blog-post" }
  #     - { label: "Title", name: "title", widget: "string", tagname: "h1" }
  #     - { label: "Slug", name: "slug", widget: "string", hint: "Only alphanumeric characters, - and _." }
  #     - { label: "Publish Date", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm", format: "YYYY-MM-DD HH:mm" }
  #     - { label: "SEO Description", name: "description", widget: "text" }
  #     - { label: "Featured Image", name: "featuredImage", widget: "image", required: false, tagname: "" }

  #     - { label: "Body", name: "body", widget: "markdown", hint: "Main content goes here." }
  - name: "artists"
    label: "Artisti"
    label_singular: "Artista"
    identifier_field: fullname
    description: >
      I fantastici artisti che lavorano nello studio.
    folder: "src/content/artists"
    slug: "{{fields.slug}}"
    summary: "{{fullname}}"
    create: true
    fields:
      - { name: "template", widget: "hidden", default: "artist" }
      - { label: "Nome Cognome", name: "fullname", widget: "string", tagname: "h1" }
      - { label: "Data di inizio", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", format: "YYYY-MM-DD" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Sotto-URL dell'artista. es: nome-cognome. USARE SOLO ALFANUMERICI E -" }
      - { label: "Ruolo/skills", name: "role", widget: "string" }
      - { label: "Mail", name: "mail", widget: "string" }
      - { label: "BIO breve", name: "description", widget: "text", hint: "Visualizzata in homepage", required: false }
      - { label: "Foto ritratto", name: "portrait", widget: "image", required: true, tagname: "" }
      - label: "BIO completa"
        name: "body"
        widget: "markdown"
      - label: "Ultimi lavori"
        name: "latestWorks"
        allow_add: true
        collapsed: true
        add_to_top: true
        summary: '{{fields.title}}'
        widget: "list"
        fields:
          - label: "Immagine"
            name: "workImage"
            widget: "image"
          - label: "Titolo"
            name: "title"
            widget: "string"
            tagname: "h3"
          - label: "Data"
            name: "date"
            widget: "datetime"
            date_format: "DD/MM/YYYY"
            hint: "Viene visualizzata come mese/anno, quindi giorno non importante"
          - label: "Commento"
            name: "comment"
            type: "text"
            required: false
            hint: "Commento/Descrizione del lavoro"
      - label: "Social Networks"
        name: "socialNetworks"
        collapsed: true
        summary: '{{fields.social}} - {{fields.url}}'
        widget: "list"
        fields:
          - label: Social
            name: social
            widget: select
            options: ["facebook", "twitter", "instagram", "linkedin", "sito web", "twitch", "skype"]
          - label: URL
            name: url
            widget: string
            hint: "Senza http:// iniziale! Deve iniziare con www."

  - label: "Pagine del sito"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - { name: "template", widget: "hidden", default: "index-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "" }
          - label: "Sezione landing"
            name: "mainSection"
            widget: "object"
            fields:
              - { label: "Titolone", name: "title", widget: "string" }
              - { label: "Sottotitolo", name: "tagline", widget: "string" }
              - { label: "Immagine a lato", name: "featuredImage", widget: "image" }
              - { label: "Immagine sfondo", name: "backgroundImage", widget: "image" }
              - label: "Pulsante call to action"
                name: "cta"
                widget: "object"
                fields:
                  - name: "ctaText"
                    label: "Testo pulsante"
                    widget: "string"
                  - name: "ctaLink"
                    label: "Link"
                    widget: "string"
                    hint: "inserire il sotto-url a cui rimandare es. /contact"
          - label: "Ci hanno scelto"
            name: "sponsorSection"
            widget: "object"
            fields:
              - label: "Sponsors"
                name: "sponsors"
                allow_add: true
                collapsed: true
                add_to_top: true
                summary: '{{fields.name}}'
                widget: "list"
                fields:
                  - { label: "Nome", name: "name", widget: "string" }
                  - { label: "Logo", name: "image", widget: "image" }
          - { label: "Testo", name: "body", widget: "markdown" }
          
      - label: "Lo Studio"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { name: "template", widget: "hidden", default: "about-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "about" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Descrizione Co-working", name: "coworkingDescription", widget: "markdown" }
          - { label: "Descrizione completa studio", name: "body", widget: "markdown" }
          - label: "Pulsante call to action"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "Testo pulsante"
                widget: "string"
              - name: "ctaLink"
                label: "Link"
                widget: "string"
                hint: "inserire il sotto-url a cui rimandare es. /contact"
          - label: "Immagini studio"
            name: "images"
            widget: "list"
            allow_add: true
            collapsed: true
            add_to_top: true
            summary: '{{fields.image}}'
            fields:
              - name: "image"
                label: "Immagine"
                widget: "image"
      - label: "Contatti"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - { name: "template", widget: "hidden", default: "contact-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "contact" }
          - { label: "Titolo", name: "title", widget: "string" }
          
          - { label: "Testo", name: "body", widget: "markdown" }
      - label: "Progetti realizzati"
        name: "projects"
        file: "src/content/pages/projects.md"
        fields:
          - { name: "template", widget: "hidden", default: "projects-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "projects" }
          - { label: "Titolo", name: "title", widget: "string" }
          - label: "Progetti"
            name: "projects"
            allow_add: true
            collapsed: true
            add_to_top: true
            summary: '{{fields.title}}'
            widget: "list"
            fields:
              - { label: "Titolo", name: "title", widget: "string" }
              - { label: "Descrizione", name: "description", widget: "text" }
              - { label: "Immagine", name: "image", widget: "image" }
          - { label: "Testo", name: "body", widget: "markdown" }
      - label: "Eventi in programma"
        name: "events"
        file: "src/content/pages/events.md"
        fields:
          - { name: "template", widget: "hidden", default: "events-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "events" }
          - { label: "Titolo", name: "title", widget: "string" }
          - label: "Eventi"
            name: "events"
            allow_add: true
            collapsed: true
            add_to_top: true
            summary: '{{fields.date_start | date('DD/MM/YYYY')}} - {{fields.name}}'
            widget: "list"
            fields:
              - { label: "Nome evento", name: "name", widget: "string" }
              - { label: "Data", name: "date_start", widget: "datetime", date_format: "DD/MM/YYYY" }
              - { label: "Data", name: "date_end", widget: "datetime", date_format: "DD/MM/YYYY" }
              - { label: "Descrizione", name: "description", widget: "text" }
              - { label: "Immagine", name: "image", widget: "image" }
          - { label: "Testo", name: "body", widget: "markdown" }
  - name: settings
    label: Impostazioni
    files:
      - name: general
        label: Generali
        file: "src/util/site.json"
        fields:
          - label: Impostazioni del sito
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Nome del sito
                required: true
              - widget: string
                name: siteUrl
                label: URL sito
                required: true
              - widget: text
                name: description
                label: Descrizione SEO sito
                default: ""
                required: false
              - widget: image
                name: logo
                label: Logo
                hint: "Dimensione 1024x1024"
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false

          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
      - label: Social Links
        name: socialLinks
        file: "src/util/socialmedia.json"
        fields:
          - label: Social Links
            name: socialLinks
            widget: list
            collapsed: true
            hint: "Here you can add social links, Click on 'Add social links'"
            fields:
              - label: "Social"
                name: "social"
                widget: "select"
                options: ["facebook", "twitter", "linkedin", "youtube", "instagram", "rss", "github", "telegram", "pinterest", "snapchat", "skype", "wordpress", "dribbble", "medium", "behance", "vk"]
                hint: "Select the Social"
              - widget: string
                name: url
                label: url
                required: true
                hint: "Paste the 'URL' of your Social media"

  - label: "Tema"
    name: "appearance"
    identifier_field: "name"
    files:
      - label: "Tema default"
        name: "themescolors"
        file: "src/util/default-colors.json"
        fields:
          - label: "Colore primario"
            name: "primaryColor"
            widget: "color"
            enableAlpha: false
            allowInput: true
          - label: "Colore sfondo"
            name: "background"
            widget: "color"
            enableAlpha: false
            allowInput: true
          - label: "Colore testo"
            name: "text"
            widget: "color"
            enableAlpha: false
            allowInput: true
