backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Uncomment local_backend when you need to develop in your local
#local_backend: true # run npx netlify-cms-proxy-server for local testing

# publish_mode: editorial_workflow

media_folder: "static/assets"
public_folder: "/assets"

i18n:
  structure: multiple_folders
  locales: [it, en]

collections:
  - name: "paintings"
    label: "Dipinti"
    label_singular: "Dipinto"
    identifier_field: title
    folder: "src/content/paintings"
    slug: "{{fields.title}}"
    summary: "{{title}} - {{image}}"
    create: true
    i18n: true
    fields:
      - { name: "template", widget: "hidden", default: "painting" }
      - { label: "Titolo", name: "title", widget: "string", tagname: "h1" }
      - { label: "Data", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Tecnica", name: "technique", widget: "string", i18n: true }
      - { label: "Dimensioni", name: "dimensions", widget: "string" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Commento", name: "body", widget: "markdown", required: false, i18n: true }
      - { label: "Link per acquisto", name: "buy_link", widget: "string", required: false }
      - { label: "Prezzo", name: "price", widget: "number", required: false }
      - { label: "Vendita diretta disponibile", name: "direct_sale", widget: "boolean", required: false }

  - name: "events"
    label: "Eventi"
    label_singular: "Evento"
    identifier_field: title
    folder: "src/content/events"
    slug: "{{fields.title}}-{{fields.date_start}}"
    summary: "{{title}}"
    create: true
    i18n: true
    fields:
      - { name: "template", widget: "hidden", default: "event" }
      - { label: "Titolo/Nome", name: "title", widget: "string", tagname: "h1" }
      - { label: "Data inizio", name: "date_start", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Data fine", name: "date_end", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Descrizione", name: "body", widget: "markdown", i18n: true }

  - name: "publications"
    label: "Pubblicazioni"
    label_singular: "Pubblicazione"
    identifier_field: title
    folder: "src/content/publications"
    slug: "{{fields.title}}"
    summary: "{{title}}"
    create: true
    i18n: true
    fields:
      - { name: "template", widget: "hidden", default: "publication" }
      - { label: "Titolo", name: "title", widget: "string", tagname: "h1" }
      - { label: "Data", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Commento", name: "body", widget: "markdown", required: false, i18n: true }
      - { label: "Link", name: "link", widget: "string", required: false }
      - label: "Immagini"
        name: "images"
        widget: "list"
        allow_add: true
        collapsed: true
        add_to_top: true
        fields:
          - { label: "Immagine", name: "image", widget: "image" }

  - label: "Pagine del sito"
    name: "pages"
    i18n: true
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
          - { name: "template", widget: "hidden", default: "index-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "" }
          - label: "Sezione landing"
            name: "mainSection"
            widget: "object"
            fields:
              - { label: "Titolo in primo piano", name: "title", widget: "string", tagname: "h1" }
              - { label: "Sottotitolo", name: "tagline", widget: "string", i18n: true }
              - { label: "Immagine a lato", name: "featuredImage", widget: "image" }
              - { label: "Immagine sfondo", name: "backgroundImage", widget: "image" }
              - label: "Pulsante call to action"
                name: "cta"
                widget: "object"
                fields:
                  - name: "ctaText"
                    label: "Testo pulsante"
                    widget: "string"
                    i18n: true
                  - name: "ctaLink"
                    label: "Link"
                    widget: "string"
                    hint: "inserire il sotto-url a cui rimandare es. /contact"
          - { label: "Testo in primo piano", name: "body", widget: "markdown", i18n: true }
          
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { name: "template", widget: "hidden", default: "about-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "about" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Foto profilo", name: "featuredImage", widget: "image" }
          - label: "Pulsante call to action"
            name: "cta"
            widget: "object"
            fields:
              - name: "ctaText"
                label: "Testo pulsante"
                widget: "string"
                i18n: true
              - name: "ctaLink"
                label: "Link"
                widget: "string"
                hint: "inserire il sotto-url a cui rimandare es. /contact"
          - { label: "Biografia completa", name: "body", widget: "markdown", i18n: true }

      - label: "Contatti"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
          - { name: "template", widget: "hidden", default: "contact-page" }
          - { name: "type", widget: "hidden", default: "page" }
          - { name: "slug", widget: "hidden", default: "contact" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Testo", name: "body", widget: "markdown", i18n: true }

      - label: "Eventi in programma"
        name: "events"
        file: "src/content/pages/events.md"
        fields:
          - { name: "template", widget: "hidden", default: "events-page" }
          - { name: "type", widget: "hidden", default: "list-page" }
          - { name: "slug", widget: "hidden", default: "events" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Testo", name: "body", widget: "markdown", i18n: true }
  - name: settings
    label: Impostazioni
    files:
      - name: general
        label: Generali
        file: "src/util/site.json"
        fields:
          - label: Impostazioni del sito
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Nome del sito
                required: true
              - widget: string
                name: siteUrl
                label: URL sito
                required: true
              - widget: text
                name: description
                label: Descrizione SEO sito
                default: ""
                required: false
              - widget: image
                name: logo
                label: Logo
                hint: "Dimensione 1024x1024"
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false

          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
      - label: Social Links
        name: socialLinks
        file: "src/util/socialmedia.json"
        fields:
          - label: Social Links
            name: socialLinks
            widget: list
            collapsed: true
            hint: "Here you can add social links, Click on 'Add social links'"
            fields:
              - label: "Social"
                name: "social"
                widget: "select"
                options: ["facebook", "twitter", "linkedin", "youtube", "instagram", "rss", "github", "telegram", "pinterest", "snapchat", "skype", "wordpress", "dribbble", "medium", "behance", "vk"]
                hint: "Select the Social"
              - widget: string
                name: url
                label: url
                required: true
                hint: "Paste the 'URL' of your Social media"

  - label: "Tema"
    name: "appearance"
    identifier_field: "name"
    files:
      - label: "Tema default"
        name: "themescolors"
        file: "src/util/default-colors.json"
        fields:
          - label: "Colore menu + fondo pagina"
            name: "primaryColor"
            widget: "color"
            enableAlpha: false
            allowInput: true
          # - label: "Colore sfondo"
          #   name: "background"
          #   widget: "color"
          #   enableAlpha: false
          #   allowInput: true
          # - label: "Colore testo"
          #   name: "text"
          #   widget: "color"
          #   enableAlpha: false
          #   allowInput: true
